version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecom_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom_dwh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: docker_default
    external: true

volumes:
  postgres_data:
